### PR TITLE
added some descriptive print to uncaught exception in calculate to aid i...

### PR DESCRIPTION
**Pull request by johano99**
I had to debug a problem in a project using airspeed that I've "inherited" where a 40Kb template threw an exception like "TypeError: coercing to Unicode: need string or buffer, NoneType found". Now, in order to find what statement in that big template file was causing the error, I simply added a small helpful? print statement describing where in the expression the error occurred.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Do you perhaps have a code example which would produce such an error?

**Comment by johano99** [comment]
Sure:

    import airspeed

    template = u"""
        #set($flag = $country.lower())
        #set($url = "$host_url/images/flags/")
        #set($flagUrl = $url + ${flag} + ".png")

        
    """
    t = airspeed.Template(template)

    model = {
        "model": {
            "host_url": u"http://whatever.com",
            "country": None
        }
    }

    s = t.merge(model)
    print s

**Comment by purcell** [comment]
This is now implemented more generally in 548777a:

Errors raised during template evaluation will get wrapped into `TemplateExecutionError`s, which provide information about where in the template the error happened.

**Comment by purcell** [comment]
The example you provided generates this exception info:

```
TemplateExecutionError: Error in template '<string>' at position 105-142 in expression: ($flagUrl = $url + ${flag} + ".png")

TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by purcell** [comment]
Released as 0.5.1. Thanks!

**Pull request closed without merging**
