### PR TITLE
Tests now work with Python 3.x

### PR DESCRIPTION
**Pull request by thorsteneb**
Use imp or importlib for reload depending on Python version
Replace all assertEquals with assertEqual
Replace assert_ with assertTrue

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, but please can you clarify? The tests were already working with Python 3.x, e.g. see https://travis-ci.org/purcell/airspeed/builds/601039003

**Comment by thorsteneb** [comment]
reload() needed a change for Python 3.x, it requires importlib from 3.4 on. As-is, the test module was failing on the reload() part. See also https://www.geeksforgeeks.org/reloading-modules-python/
The other changes were made to stop deprecation warnings.

**Comment by purcell** [comment]
Thanks, it's hard to tell, though, because the file is just one big diff. Did you change line endings, or indentation, or something?

**Comment by thorsteneb** [comment]
I noticed that. Line ending is entirely possible. It shouldn’t have, should all stay LF ... and I can check.

Yours

Thorsten Behrens
(Sent from mobile)
________________________________

**Comment by purcell** [comment]
Yes, the line endings changed to DOS. I've fixed that up, squashed the commit, and merged in 7cb5723 - thanks!

**Comment by thorsteneb** [comment]
Thank you. I’ll take a look at core.autocrlf, that should not have happened.

In the process I learned about .gitattributes “* text=auto”, as a way to set that for the project.

All the best
Thorsten

**Pull request closed without merging**
