### PR TITLE
better error message

### PR DESCRIPTION
**Pull request by jmdcal**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks for this.

**Comment by jmdcal** [comment]
actually I allowed for these to happen due to the code I am given from a 3rd party,
 so you might want to have an option to allow the redefining of macros.

**Comment by purcell** [comment]
What does Velocity itself do?

**Comment by jmdcal** [comment]
it is allowed by option http://velocity.apache.org/engine/releases/velocity-1.7/apidocs/org/apache/velocity/runtime/RuntimeConstants.html#VM_PERM_ALLOW_INLINE_REPLACE_GLOBAL

**Comment by purcell** [comment]
Thanks. Yes, it might make sense to support the same options, then...

**Pull request merged**
