### PR TITLE
Add replace all string method

### PR DESCRIPTION
**Pull request by juankaram**
Hi Mantainers,

I'm happy to make any additional changes if you find it necessary.

Thank you for the work in your library

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, this looks good! It would also need a unit test please. :-)

**Comment by juankaram** [comment]
You got it! Thanks for the review.

**Comment by purcell** [comment]
Merged, thanks.

**Comment by purcell** [comment]
Released as 0.5.13.

**Pull request merged**
